#!/bin/bash

cd /usr/share/python3
. venv/bin/activate

echo "from app import app" > shopdb.py
export FLASK_APP=shopdb.py

flask db init
flask db migrate
flask db upgrade

rm shopdb.py

gunicorn wsgi:app -b 0.0.0.0:5000
